[package]
name = "overlay-ui"
publish.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
egui.workspace = true
windows.workspace = true
engine-api.workspace = true

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.22"
